# Generated by Django 3.2.3 on 2021-06-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_post_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
