# Generated by Django 3.2.3 on 2021-07-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='.png', null=True, upload_to='images/profiles/'),
        ),
    ]
