# Generated by Django 3.2.3 on 2021-07-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='images/default_pic_wHQDZUq.png', null=True, upload_to='images/profiles/'),
        ),
    ]
